CRITICAL_END_TO_END_FLOWS = [
    {
        "id": "orders_upload_parse_review",
        "label": "הזמנות > העלאת PDF > פרסור > בדיקת שדות",
        "category": "orders",
        "sandbox_only": True,
    },
    {
        "id": "orders_manual_create_multi_item",
        "label": "הזמנות > יצירה ידנית > כמה מוצרים > מסמכים",
        "category": "orders",
        "sandbox_only": True,
    },
    {
        "id": "orders_pdf_to_finalize_full_artifacts",
        "label": "הזמנות > PDF > finalize > כל המסמכים > Drive > היסטוריה",
        "category": "orders",
        "sandbox_only": True,
    },
    {
        "id": "orders_with_transport_label_bundle",
        "label": "הזמנות > יצירה עם משלוח > מדבקות > merged > ווטסאפ",
        "category": "orders",
        "sandbox_only": True,
    },
    {
        "id": "orders_delivery_only_finalize",
        "label": "הזמנות > תעודת משלוח בלבד > finalize > היסטוריה",
        "category": "orders",
        "sandbox_only": True,
    },
    {
        "id": "orders_invoice_only_finalize",
        "label": "הזמנות > חשבונית בלבד > finalize > תשלומים",
        "category": "orders",
        "sandbox_only": True,
    },
    {
        "id": "orders_partial_delivery_followup",
        "label": "הזמנות > אספקה חלקית > יתרה > תעודת משלוח נוספת",
        "category": "orders",
        "sandbox_only": True,
    },
    {
        "id": "quote_to_order_history_flow",
        "label": "הצעת מחיר > היסטוריית הצעות > צור הזמנה",
        "category": "orders",
        "sandbox_only": True,
    },
    {
        "id": "orders_previous_document_clone_flow",
        "label": "הזמנות > שכפל ממסמך קודם > טעינה למסך > finalize",
        "category": "orders",
        "sandbox_only": True,
    },
    {
        "id": "delivery_confirmation_send",
        "label": "אישורי מסירה > העלאה > שליחה > עדכון היסטוריה",
        "category": "delivery",
        "sandbox_only": True,
    },
    {
        "id": "delivery_confirmation_manual_close_only",
        "label": "אישורי מסירה > העלאה בלבד > אישור ידני ללא שליחה",
        "category": "delivery",
        "sandbox_only": True,
    },
    {
        "id": "finance_invoice_parse_to_report_due_date",
        "label": "כספים > פרסור חשבונית > שיוך לדיווח > ייצוא",
        "category": "finance",
        "sandbox_only": False,
    },
    {
        "id": "finance_scanned_multi_invoice_split",
        "label": "כספים > מסמך סרוק מרובה חשבוניות > חיתוך > שמירה",
        "category": "finance",
        "sandbox_only": False,
    },
    {
        "id": "finance_eml_to_pdf_and_save",
        "label": "כספים > העלאת EML > המרה ל-PDF > פרסור > שמירה",
        "category": "finance",
        "sandbox_only": False,
    },
    {
        "id": "finance_unpaid_invoice_to_payments_table",
        "label": "כספים > טרם שולם > הוספה אוטומטית לטבלת לתשלום",
        "category": "finance",
        "sandbox_only": False,
    },
    {
        "id": "payments_collection_payment_lifecycle",
        "label": "תשלומים > יצירה/עריכה/סינון/שולם > רענון state",
        "category": "payments",
        "sandbox_only": False,
    },
    {
        "id": "marketing_work_managers_export_wix_csv",
        "label": "שיווק > מאגר מנהלי עבודה > פילטר > ייצוא Wix CSV",
        "category": "marketing",
        "sandbox_only": False,
    },
    {
        "id": "marketing_price_update_quote_roundtrip",
        "label": "שיווק > ייצוא מחירים > ייבוא שינויים > צור הצעה עדכנית > שלח",
        "category": "marketing",
        "sandbox_only": False,
    },
    {
        "id": "marketing_sandbox_quote_test_send",
        "label": "שיווק > צור סנדבוקס ושלח טסט",
        "category": "marketing",
        "sandbox_only": True,
    },
    {
        "id": "inventory_supplier_delivery_note_to_stock",
        "label": "מלאי > תעודת משלוח ספק > שמירה > עדכון מלאי",
        "category": "inventory",
        "sandbox_only": False,
    },
    {
        "id": "inventory_purchase_order_create_send_cycle",
        "label": "מלאי > הזמנת רכש פנימית > יצירה > מייל/ווטסאפ > היסטוריה",
        "category": "inventory",
        "sandbox_only": False,
    },
    {
        "id": "inventory_finish_stock_restore_after_sandbox",
        "label": "מלאי > החזרת ניכויי סנדבוקס > אימות כמויות",
        "category": "inventory",
        "sandbox_only": False,
    },
    {
        "id": "hr_monthly_payslip_package_send",
        "label": "עובדים ושכר > תלושים להפקה > קבצים תומכים > שליחה לרו\"ח",
        "category": "hr",
        "sandbox_only": False,
    },
    {
        "id": "admin_refresh_pazomat_and_sibus",
        "label": "מנהלה > רענון פזומט + סיבוס > סנכרון מלא",
        "category": "admin",
        "sandbox_only": False,
    },
]
