import Foundation

/// תרגום מפתחות דאטה לתוויות בעברית עבור מסכי פירוט.
enum FieldLabels {
    static let map: [String: String] = [
        "customer_name": "שם לקוח",
        "customer_id": "ח.פ / ע.מ",
        "customer_domain": "תחום",
        "customer_email": "אימייל לקוח",
        "customer_phone": "טלפון לקוח",
        "contact_person": "איש קשר",
        "contact_name": "איש קשר",
        "contact_phone": "טלפון איש קשר",
        "secondary_contact_name": "איש קשר נוסף",
        "secondary_contact_phone": "טלפון נוסף",
        "phone": "טלפון",
        "phone_1": "טלפון 1",
        "phone_2": "טלפון 2",
        "phone_3": "טלפון 3",
        "mobile": "נייד",
        "emails": "אימייל",
        "email": "אימייל",
        "address": "כתובת",
        "city": "עיר",
        "zip": "מיקוד",
        "country": "מדינה",
        "delivery_address": "כתובת אספקה",
        "project": "פרויקט",
        "po_number": "מס' הזמנה",
        "po_date": "תאריך הזמנה",
        "quote_number": "מס' הצעה",
        "quote_date": "תאריך הצעה",
        "payment_terms_days": "ימי אשראי",
        "payment_terms_label": "תנאי תשלום",
        "subtotal": "לפני מע\"מ",
        "vat": "מע\"מ",
        "total": "סה\"כ",
        "created_at": "נוצר",
        "updated_at": "עודכן",
        "input_source": "מקור",
        "mode": "מצב",
        "source_mode": "מצב מקור",
        "delivery_number": "מס' תעודת משלוח",
        "tax_invoice_number": "מס' חשבונית מס",
        "proforma_invoice_number": "חשבונית עסקה",
        "receipt_number": "מס' קבלה",
        "accounting_key": "מפתח הנה\"ח",
        "income_amount": "הכנסות",
        "payment_amount": "תקבולים",
        "balance_amount": "יתרה",
        "remarks": "הערות",
        "notes": "הערות",
        "note_text": "הערה",
        "order_note_text": "הערת הזמנה",
        "active": "פעיל",
        "send": "שליחה",
        "department": "מחלקה",
        "supplier_name": "ספק",
        "reference_number": "מס' אסמכתא",
        "allocation_number": "מס' הקצאה",
        "service_or_product": "שירות / מוצר",
        "invoice_date": "תאריך חשבונית",
        "invoice_number": "מס' חשבונית",
        "source_file_name": "קובץ מקור",
        "amount": "סכום",
        "balance": "יתרה",
        "due_date": "תאריך יעד",
        "due_time": "שעה",
        "paid": "שולם",
        "payment_direction": "כיוון",
        "transaction_date": "תאריך תנועה",
        "value_date": "תאריך ערך",
        "account_name": "חשבון",
        "account_number": "מס' חשבון",
        "company_name": "חברה",
        "company": "חברה",
        "company_id": "ח.פ חברה",
        "operation_type": "סוג פעולה",
        "reference": "אסמכתא",
        "channel": "ערוץ",
        "fee_or_notes": "עמלה / הערות",
        "description": "תיאור",
        "receipt_date": "תאריך קבלה",
        "gross_amount": "ברוטו",
        "withholding_percent": "אחוז ניכוי",
        "withheld_amount": "סכום ניכוי",
        "paid_amount": "שולם בפועל",
        "withholding_applied": "נוכה במקור",
        "setting_key": "הגדרה",
        "setting_value": "ערך",
        "order_date": "תאריך הזמנה",
        "order_total": "סכום הזמנה",
        "target_email": "אימייל יעד",
        "signed_delivery_name": "תעודה חתומה",
        "coc_name": "תעודת COC",
        "accounting_contact_name": "איש קשר הנה\"ח",
        "month": "חודש",
        "month_key": "חודש",
        "month_label": "חודש",
        "status": "סטטוס",
        "subject": "נושא",
        "fuel_doc_number": "מסמך דלק",
        "total_amount": "סה\"כ",
        "fuel_amount": "דלק",
        "service_amount": "דמי שירות",
        "debit_date": "תאריך חיוב",
        "vehicle_count": "רכבים",
        "card_count": "כרטיסים",
        "liters_total": "ליטרים",
        "billing_period": "תקופת חיוב",
        "subtotal_amount": "לפני מע\"מ",
        "vat_amount": "מע\"מ",
        "customer_number": "מס' לקוח",
        "item_description": "תיאור פריט",
        "item_name": "פריט",
        "item_sku": "מק\"ט",
        "item_quantity": "כמות",
        "item_unit": "יחידה",
        "item_unit_price": "מחיר יחידה",
        "item": "פריט",
        "product": "מוצר",
        "material": "חומר",
        "supplier": "ספק",
        "supplier_sku": "מק\"ט ספק",
        "length": "אורך",
        "width": "רוחב",
        "thickness": "עובי",
        "price": "מחיר",
        "unit": "יחידה",
        "actual_quantity": "כמות במלאי",
        "unit_count": "יחידות",
        "quantity": "כמות",
        "name": "שם",
        "company_phone": "טלפון חברה",
        "direct_phone": "טלפון ישיר",
        "delivery_note_number": "מס' תעודת משלוח",
        "delivery_date": "תאריך משלוח",
        "parser_name": "פרסר",
        "source_document_name": "מסמך מקור",
        "full_name": "שם מלא",
        "id_number": "ת.ז",
        "employment_type": "סוג העסקה",
        "active_status": "סטטוס",
        "start_date": "תחילת עבודה",
        "base_salary": "שכר בסיס",
        "hourly_rate": "תעריף שעה",
        "pension_fund": "קרן פנסיה",
        "employee_name": "עובד",
        "regular_hours": "שעות רגילות",
        "overtime_hours": "שעות נוספות",
        "hours_file_name": "קובץ שעות",
        "gross_amount_payroll": "ברוטו",
        "net_amount": "נטו",
        "salary_paid": "שולם",
        "salary_paid_date": "תאריך תשלום",
        "salary_reference": "אסמכתא",
        "payslip_file_name": "תלוש",
        "employee_contribution": "הפרשת עובד",
        "employer_contribution": "הפרשת מעסיק",
        "compensation_amount": "פיצויים",
        "paid_date": "תאריך תשלום",
        "category": "קטגוריה",
        "title": "כותרת",
        "file_name": "קובץ",
        "send_mode": "אופן שליחה",
        "sent_to": "נשלח אל",
        "sent_at": "נשלח בתאריך",
        "employees_total": "מס' עובדים",
        "gross_total_label": "סה\"כ ברוטו",
        "attachments_count": "קבצים מצורפים",
        "action_type": "סוג פעולה",
        "result": "תוצאה",
        "comm_status": "סטטוס תקשורת",
        "comm_sent_at": "נשלח",
        "mail_subject": "נושא מייל",
        "mail_sent_at": "מייל נשלח",
        "message": "הודעה",
        "completed_at": "הושלם",
        "current_employer": "מעסיק נוכחי",
        "current_workplace": "אתר נוכחי",
        "project_manager_match": "התאמת מנהל פרויקט",
        "details_url": "קישור",
        "site_address": "כתובת אתר",
        "tax_id": "ח.פ",
        "history_dates": "תאריכים קודמים",
        "last_update_date": "עודכן",
        "creation_date": "נוצר",
        "item_id": "מזהה פריט",
        "component_id": "מזהה רכיב",
        "kind": "סוג",
        "pricing_unit": "יחידת תמחור",
        "default_width_m": "רוחב ברירת מחדל (מ')",
        "default_length_m": "אורך ברירת מחדל (מ')",
        "labor_minutes": "דקות עבודה",
        "labor_hour_cost": "עלות שעת עבודה",
        "shipping_total_cost": "עלות משלוח",
        "order_quantity": "כמות להזמנה",
        "unit_cost": "עלות יחידה",
        "waste_percent": "אחוז פחת",
        "bank_name": "בנק",
        "bank_branch": "סניף",
        "bank_account": "חשבון בנק",
    ]

    /// שדות טכניים שלא מציגים במסך פירוט.
    static let hiddenKeys: Set<String> = [
        "row_id", "history_id", "reminder_id", "customer_guid", "customer_key", "fulfillment_id",
        "record_id", "employee_id", "quote_document_id", "po_document_id", "gmail_message_id",
        "source_file_path", "source_local_path", "local_path", "details_json", "vehicles_json",
        "cards_json", "supporting_summaries_json", "sizes_json", "_sheet_row", "_sheet_title",
        "drive_folder_id", "drive_file_id", "hours_drive_file_id", "payslip_drive_file_id",
        "split_report_drive_file_id", "proof_drive_file_id", "source_drive_file_id",
        "invoice_drive_file_id", "signed_delivery_drive_file_id", "coc_drive_file_id",
        "order_drive_folder_id", "quote_drive_file_id", "synced_at", "migration_batch",
        "editable_company", "editable_tax_id", "editable_site_address", "editable_contact_name",
        "editable_order_date", "editable_item", "editable_contact_phone", "source_key",
        "bank_details_updated_sent", "review_pending", "dismissed", "selected_size_id",
    ]

    /// מפתחות שהערך שלהם הוא קישור שאפשר לפתוח.
    static let linkKeys: Set<String> = [
        "drive_folder_url", "drive_url", "hours_drive_url", "payslip_drive_url",
        "split_report_drive_url", "proof_drive_url", "source_drive_url", "details_url",
        "order_drive_folder_url", "quote_drive_url",
    ]

    static func label(for key: String) -> String {
        if let label = map[key] { return label }
        return key.replacingOccurrences(of: "_", with: " ")
    }
}
